AWSTemplateFormatVersion: 2010-09-09

Resources:
  ClofioAgent:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: clofio-agent
      Policies:
        - PolicyName: clofio-agent-permission
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'resource-explorer-2:ListIndexes'
                  - 'resource-explorer-2:ListViews'
                  - 'resource-explorer-2:CreateView'
                  - 'resource-explorer-2:Search'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource:
                  - 'arn:aws:s3:::clofio-cur-bucket'
                  - 'arn:aws:s3:::clofio-cur-bucket/*'
              - Effect: Allow
                Action:
                  - 'cloudwatch:Describe*'
                  - 'cloudwatch:Get*'
                  - 'cloudwatch:List*'
                  - 'ec2:Describe*'
                  - 'ec2:Get*'
                  - 'elasticloadbalancing:Describe*'
                  - 'rds:Describe*'
                  - 'rds:List*'
                  - 'route53:List*'
                Resource: '*'
      Tags:
        - Key: CreatedBy
          Value: clofio-cloudformation-template

  UserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ClofioCrossAccountPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource: arn:aws:iam::*:role/ClofioCrossAccountRole
      Users:
        - !Ref ClofioAgent

  ClofioCurS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: clofio-cur-bucket
      Tags:
        - Key: CreatedBy
          Value: clofio-cloudformation-template

  ClofioCurS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ClofioCurS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - 's3:GetBucketAcl'
              - 's3:GetBucketPolicy'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ClofioCurS3Bucket
            Condition:
              StringEquals:
                'aws:SourceArn': !Join
                  - ':'
                  - - 'arn:aws:cur:us-east-1'
                    - !Ref "AWS::AccountId"
                    - 'definition/*'
                'aws:SourceAccount': !Ref "AWS::AccountId"
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ClofioCurS3Bucket
                - '/*'
            Condition:
              StringEquals:
                'aws:SourceArn': !Join
                  - ':'
                  - - 'arn:aws:cur:us-east-1'
                    - !Ref "AWS::AccountId"
                    - 'definition/*'
                'aws:SourceAccount': !Ref "AWS::AccountId"

  ClofioCurReportDefinition:
    Type: 'AWS::CUR::ReportDefinition'
    DependsOn: ClofioCurS3BucketPolicy
    Properties:
      AdditionalSchemaElements:
        - RESOURCES
      Compression: GZIP
      Format: textORcsv
      RefreshClosedReports: true
      ReportName: clofio-data-ingestion
      ReportVersioning: OVERWRITE_REPORT
      S3Bucket: !Ref ClofioCurS3Bucket
      S3Prefix: reports
      S3Region: !Ref 'AWS::Region'
      TimeUnit: DAILY